@HOSTNAME=localhost
@PORT=4000
@CONFIRMATION_TOKEN=678698
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJqb2huLmRvZUBnbWFpbC5jb20iLCJpYXQiOjE3MjE3MTQ3OTMsImV4cCI6MTczNzI2Njc5M30.a4o3w8m5WunrMKMOlEY-tejjOLnBlNutnsHh1bHyYv8

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/create-account
Content-Type: application/json

{
  "username": "john doe",
  "email": "john.doe@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/confirm-account
Content-Type: application/json

{
  "token": "{{CONFIRMATION_TOKEN}}"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "Password123"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/request-code
Content-Type: application/json

{
  "email": "john.doe@gmail.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "john.doe@gmail.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/validate-password-token
Content-Type: application/json

{
  "token": "{{CONFIRMATION_TOKEN}}"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/update-password/{{CONFIRMATION_TOKEN}}
Content-Type: application/json

{
  "password": "Password123",
  "password_confirmation": "Password123"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/user
Authorization: Bearer {{ACCESS_JWT}}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/google/authentication
