@HOSTNAME=localhost
@PORT=4000
@CONFIRMATION_TOKEN=540796
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImVtYWlsIjoiZW1lcnNvbi56YXBhdGFAZ21haWwuY29tIiwiaWF0IjoxNzIyODI4Mjg3LCJleHAiOjE3MzgzODAyODd9.0eF44rPwuoyO5GCUQjPVuIySn9O69BgTBdJ-E2ETcXg

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/create-account
Content-Type: application/json

{
  "username": "John doe",
  "email": "john.doe@mail.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/confirm-account
Content-Type: application/json

{
  "token": "{{CONFIRMATION_TOKEN}}"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@mail.com",
  "password": "password"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/request-code
Content-Type: application/json

{
  "email": "john.doe@mail.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "john.doe@mail.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/validate-password-token
Content-Type: application/json

{
  "token": "{{CONFIRMATION_TOKEN}}" 
}

###

PUT http://{{HOSTNAME}}:{{PORT}}/api/auth/update-password/{{CONFIRMATION_TOKEN}}
Content-Type: application/json

{
  "password": "Password123",
  "password_confirmation": "Password123"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/user
Authorization: Bearer {{ACCESS_JWT}}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/google/authentication
