@hostname=localhost
@port=4000

POST http://{{hostname}}:{{port}}/api/auth/create-account
Content-Type: application/json

{
  "username": "emerson",
  "email": "emerson.zapatarivas@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://{{hostname}}:{{port}}/api/auth/login
Content-Type: application/json

{
  "email": "emerson.zapatarivas@gmail.com",
  "password": "password"
}

###

GET http://{{hostname}}:{{port}}/api/auth/google/authentication
